#!/bin/bash
# Configurar TODAS las variables de entorno en Vercel para app.smarterbot.cl

echo "🔧 Configurando variables de entorno en Vercel..."
echo ""

# Información encontrada
SUPABASE_URL="https://rjfcmmzjlguiititkmyh.supabase.co"
SUPABASE_PROJECT="rjfcmmzjlguiititkmyh"

echo "📋 Variables que necesitamos configurar:"
echo "=========================================="
echo ""
echo "1️⃣ OPCIÓN RÁPIDA - MODO DEMO (Funciona inmediatamente)"
echo "--------------------------------------------------------"
echo "Ve a: https://vercel.com/smartercl/app-smarterbot/settings/environment-variables"
echo ""
echo "Agrega UNA sola variable:"
echo ""
echo "Key: NEXT_PUBLIC_DEMO_MODE"
echo "Value: true"
echo "Environment: Production ✅"
echo ""
echo "Luego haz clic en 'Save' y Vercel rebuildeará automáticamente."
echo ""
echo "=========================================="
echo ""
echo "2️⃣ OPCIÓN COMPLETA - PRODUCCIÓN REAL"
echo "--------------------------------------------------------"
echo ""
echo "SUPABASE (encontradas):"
echo "----------------------"
echo "NEXT_PUBLIC_SUPABASE_URL=$SUPABASE_URL"
echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=PENDIENTE (necesitas obtenerla de Supabase Dashboard)"
echo ""
echo "🔗 Ve a: https://supabase.com/dashboard/project/$SUPABASE_PROJECT/settings/api"
echo "   Copia el 'anon public' key"
echo ""
echo "CLERK (necesitas configurar):"
echo "-----------------------------"
echo "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=PENDIENTE"
echo "CLERK_SECRET_KEY=PENDIENTE"
echo ""
echo "🔗 Ve a: https://dashboard.clerk.com/"
echo "   Copia las API Keys de tu aplicación"
echo ""
echo "OTRAS:"
echo "------"
echo "NEXT_PUBLIC_APP_URL=https://app.smarterbot.cl"
echo "NODE_ENV=production"
echo ""
echo "=========================================="
echo ""
echo "💡 RECOMENDACIÓN:"
echo "=================="
echo "1. Usa MODO DEMO primero (1 variable, 2 minutos)"
echo "2. Verifica que funcione"
echo "3. Luego configura Clerk + Supabase ANON_KEY para producción real"
echo ""
echo "🚀 Una vez configuradas, Vercel rebuildeará automáticamente"
echo "   En 2-3 minutos estará disponible en https://app.smarterbot.cl"
