#!/bin/bash

echo "🔄 Guía de Migración al Workflow Funcional"
echo "=========================================="
echo ""
echo "✅ Workflow que FUNCIONA:"
echo "   https://n8n.smarterbot.cl/workflow/BWdJF4keyeKKIfaS"
echo ""
echo "❌ Workflow que FALLA:"
echo "   https://n8n.smarterbot.cl/workflow/12YQs59zqfw0jjKl"
echo ""
echo "📋 PASOS PARA MIGRAR:"
echo ""
echo "OPCIÓN A - Duplicar el Funcional (RECOMENDADO)"
echo "----------------------------------------------"
echo "1. Abrir: https://n8n.smarterbot.cl/workflow/BWdJF4keyeKKIfaS"
echo "2. Click en '...' (menú superior derecha)"
echo "3. Click en 'Duplicate'"
echo "4. Renombrar a: 'GitHub Templates - Automation Manifest'"
echo "5. Modificar el query del nodo GitHub a:"
echo "   repo:SmarterCL/n8n-workflows path:templates/ extension:json"
echo "6. Save"
echo "7. Execute para probar"
echo ""
echo "OPCIÓN B - Copiar Credential al Workflow Roto"
echo "---------------------------------------------"
echo "1. En workflow funcional, ver qué credential usa"
echo "2. Copiar nombre del credential"
echo "3. Ir al workflow roto"
echo "4. En cada nodo GitHub, cambiar a ese credential"
echo "5. Remove SSL certificate si tiene"
echo "6. Save y test"
echo ""
echo "OPCIÓN C - Copiar Nodos"
echo "----------------------"
echo "1. En workflow funcional: Select nodo GitHub"
echo "2. Copy (Ctrl+C)"
echo "3. Ir al workflow roto"
echo "4. Delete nodo problemático"
echo "5. Paste (Ctrl+V)"
echo "6. Reconectar flows"
echo "7. Save y test"
echo ""
echo "✨ DESPUÉS DE MIGRAR:"
echo ""
echo "1. Test que funcione el search"
echo "2. Agregar procesamiento de resultados"
echo "3. Conectar con automation-manifest.json"
echo "4. Schedule para ejecutar cada hora"
echo "5. Agregar webhook a API Gateway"
echo ""
echo "📚 Ver guía completa en:"
echo "   /root/N8N-WORKING-WORKFLOW-ANALYSIS.md"
echo ""
