#!/bin/bash
# Setup app.smarterbot.cl en Vercel desde cero

echo "🚀 Configurando app.smarterbot.cl en Vercel..."
echo ""

# Variables necesarias
PROJECT_NAME="app-smarterbot"
REPO="SmarterCL/app.smarterbot.cl"
DOMAIN="app.smarterbot.cl"

echo "📦 Paso 1: Importar proyecto desde GitHub"
echo "-------------------------------------------"
echo "Ve a: https://vercel.com/new"
echo ""
echo "1. Click en 'Import Git Repository'"
echo "2. Busca: $REPO"
echo "3. Click 'Import'"
echo ""

echo "⚙️ Paso 2: Configurar Build Settings"
echo "-------------------------------------------"
echo "Framework Preset: Next.js"
echo "Root Directory: ./"
echo "Build Command: pnpm build (default)"
echo "Output Directory: .next (default)"
echo "Install Command: pnpm install (default)"
echo ""

echo "🔐 Paso 3: Agregar Environment Variables"
echo "-------------------------------------------"
echo "Agrega estas variables ANTES de hacer deploy:"
echo ""
echo "OPCIÓN A - MODO DEMO (Rápido):"
echo "------------------------------"
echo "NEXT_PUBLIC_DEMO_MODE=true"
echo ""
echo "OPCIÓN B - PRODUCCIÓN REAL:"
echo "------------------------------"
echo "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_test_XXXXX"
echo "CLERK_SECRET_KEY=sk_test_XXXXX"
echo "NEXT_PUBLIC_SUPABASE_URL=https://xxxxx.supabase.co"
echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGci..."
echo "NEXT_PUBLIC_APP_URL=https://app.smarterbot.cl"
echo "NODE_ENV=production"
echo ""

echo "🌐 Paso 4: Configurar Dominio Personalizado"
echo "-------------------------------------------"
echo "Una vez deployado:"
echo "1. Ve a Settings → Domains"
echo "2. Agrega: $DOMAIN"
echo "3. Vercel te dará los DNS records"
echo "4. Configúralos en Cloudflare/MainKey"
echo ""

echo "✅ Paso 5: Verificar Deployment"
echo "-------------------------------------------"
echo "URL: https://$DOMAIN/dashboard"
echo "Debe mostrar el dashboard sin error de configuración"
echo ""

echo "�� Links Útiles:"
echo "-------------------------------------------"
echo "Vercel Dashboard: https://vercel.com/smartercl"
echo "Nuevo Proyecto: https://vercel.com/new"
echo "Clerk Keys: https://dashboard.clerk.com/"
echo "Supabase Keys: https://app.supabase.com/"
echo ""

echo "💡 Recomendación: Usa MODO DEMO primero para verificar que funciona"
echo "   Luego configura las claves reales de producción"
